### ISSUE TITLE
task1 error - cannot change working directory

### ISSUE THREAD

**Issue by goertzenlr** [vlothec/TRASH#2]
entire TRASH executable downloaded, (trash_install succeeds as test), new R in conda env. - test run on 30kb fasta:

[1] "Currently registered parallel backend name, version and cores"
[1] "doParallelMC"
[1] "1.0.17"
[1] 1
[1] "Sequences to analyse:"
  file.name fasta.name
2   test.fa    Contig1
[1] "2023-05-15 09:47:17 CDT"
[1] "Working on sequence 1"
[1] "Repeat Identification new"
[1] "test_out1"
[1] "test.fa"
Error in { : task 1 failed - "cannot change working directory"
Calls: %dopar% -> <Anonymous>
Execution halted

**Comment by vlothec** [comment]
Hi, can you provide the command you used? The only way I can replicate this error is when the output directory has a typo. The output directory also needs to be an absolute path, or no path at all (then output is placed where the command is run from).

**Comment by goertzenlr** [comment]
thanks, my error.  I took the instructions to mean if no path info _in front of_ the output directory name, it would be placed where command is run from.  

- proceeds now but hits another (path related?) bump:

./TRASH_run.sh test.fa 

...
...

[1] "Currently registered parallel backend name, version and cores"
[1] "doParallelMC"
[1] "1.0.17"
[1] 1
[1] "Sequences to analyse:"
  file.name fasta.name
2   test.fa    Contig1
[1] "2023-05-16 08:32:02 CDT"
[1] "Working on sequence 1"
[1] "Repeat Identification new"
[1] "/home/Documents/installs/TRASH"
[1] "test.fa"
[[1]]
NULL

          used  (Mb) gc trigger  (Mb) max used  (Mb)
Ncells 2595200 138.6    4868417 260.1  4868417 260.1
Vcells 4447698  34.0   10146329  77.5  7160664  54.7
[1] "Finished working on sequence 1"
[1] "2023-05-16 08:32:08 CDT"
[1] "saving repeats"
[1] "/home/Documents/installs/TRASH"
character(0)
Error in file(file, "rt") : cannot open the connection
Calls: read.csv -> read.table -> file
In addition: Warning message:
In file(file, "rt") : cannot open file 'NA': No such file or directory
Execution halted


- in various tests, output dirs with debug files and .out files are correctly placed in current dir (above) or where --o absolute path specified

**Comment by vlothec** [comment]
Yes, the run goes through almost to the end. It seems like there are no repeats identified within the test.fa sequence. Is it a particuarly short sequence? Maybe there is something else that would throw TRASH off. Seems like nothing is identified first and then crashes trying to plot it. 

If you try to test TRASH using provided test sequence (example_run/CP068268_39050443_39150442.fa), you might see if the program works as intended for you.

**Comment by goertzenlr** [comment]
correct, 30 kb fragment used to test, likely no major repeats, thought it might have clean exit status.  will test with more realistic scaffold. thanks
