### ISSUE TITLE
Calls: %dopar% -> <Anonymous>

### ISSUE THREAD

**Issue by zhouxp9709** [vlothec/TRASH#23]
Hello.
Thank you for developing TRASH, I am getting the following error when running TRASH:

```
Error in { : task 1 failed - "'length = 28' in coercion to 'logical(1)'"
Calls: %dopar% -> <Anonymous>
Execution halted
```
Thank you.

**Comment by PraveenOraon** [comment]
Same Error what was the solution for this error. @zhouxp9709 
`Error in { : task 1 failed - "'length = 132' in coercion to 'logical(1)'"
Calls: %dopar% -> <Anonymous>
Execution halted`
