### ISSUE TITLE
HOR run details

### ISSUE THREAD

**Issue by HaoWangLYL** [vlothec/TRASH#4]
hello  
can you apply an example_run  order?
thank you

**Comment by vlothec** [comment]
Hi, what do you mean by applying an example_run order? If you'd like to re-create the example run, you can use a command
`{TRASH_dir}/TRASH_run.sh {TRASH_dir}/example_run/CP068268_39050443_39150442.fa --o {output_dir}`

**Comment by HaoWangLYL** [comment]
i want to know how to use the HOR module, because when i use this pipline in the given order, it cant product the result and png about HOR.




635169288
***@***.***



&nbsp;

**Comment by vlothec** [comment]
The HOR module requires repeat classification, so only one repeat family is analysed. The first step is to add a sequence template information that will be used for this classification. For example a file called "sequence_template.csv" that looks like:
'name,length,seq
CEN178,178,AGTATAAGAACTTAAACCGCAACCGATCTTAAAAGCCTAAGTAGTGTTTCCTTGTTAGAAGACACAAAGCCAAAGACTCATATGGACTTTGGCTACACCATGAAAGCTTTGAGAAGCAAGAAGAAGGTTGGTTAGTGTTTTGGAGTCGAATATGACTTGATGTCATGTGTATGATTG'
It can be used to classify Arabidopsis thaliana CEN178 repeats. In the output, these will have a "CEN178" class assigned. Add "--seqt {dir}/sequence_template.csv" to the command to use them. 
With that, CEN178 repeats are available for the HOR analysis by adding "--horclass CEN178" to the command.
A full command that will include a HOR run looks like:
'{TRASH_dir}/TRASH_run.sh {fasta_dir}/xxx.fa --o {output_dir} --seqt {dir}/sequence_template.csv --horclass NNN'

**Comment by vlothec** [comment]
> Why in my results all the calss is NA?&nbsp; 635169288 ***@***.*** &nbsp;

See the comment above. Without appropriate sequence templates, no class will be assigned (NA).

**Comment by HaoWangLYL** [comment]
yes, i got it.thank you&nbsp;
&nbsp;


635169288
***@***.***



&nbsp;
