### ISSUE TITLE
R  visualization

### ISSUE THREAD

**Issue by duhuipeng** [vlothec/TRASH#5]
I ran through your first step using the fa file under example_run
These are all the files it generated，as follow：
![image](https://github.com/vlothec/TRASH/assets/58722433/930028ed-aaed-4260-a4a2-7a788d26c078)

But now I want to use R for visualization, and I don't know if there is something wrong with the file I entered
The code I run is as follows：
Rscript TRASH_run.R ../example_run/all.repeats.from.CP068268_39050443_39150442.fa.csv
made the following error：
![image](https://github.com/vlothec/TRASH/assets/58722433/c361237d-9592-4dd5-8219-a73203a27825)
now I want to draw a picture of your article, as follow：
![image](https://github.com/vlothec/TRASH/assets/58722433/1bb68ba4-ae69-4485-bd12-e14fee593685)
How do I do that? 
Could you please provide the running code to draw these diagrams？
As the result of the example_run run, could you provide the R running code to run this example？
Best
HuipengDu

**Comment by vlothec** [comment]
Hello, TRASH is not able to produce these published images, as they're results of a much longer analysis of multiple genomes, where TRASH repeat identification was just the first step. 

By default, a circos plot is drawn to visualise repeat locations. Alternatively, after adding `--simpleplot` to the run command, for each sequence a plot will be drawn with repeat locations on the x axis and their sizes on the y axis. 

Panel c plotting is `plot(x = repeats$start, y = repeats$HOR_score, type = "h", col = "blue", xlim = c(cen_start, cen_end)`
Panel b plot is done similarily, using data of CEN178 repeats from 330 centromeres, averaged over their lengths in 100 bins. Label formatting for both has been done in Photoshop. Please email me at pw457@cam.ac.uk for details, as it's not relevant to this GitHub repository.
