### ISSUE TITLE
cluster

### ISSUE THREAD

**Issue by duhuipeng** [vlothec/TRASH#7]
Dear author

The  article said the proportion of AthCEN178 between the two strains of each chromosome was calculated and divided into 9 groups by cluster clustering.

How does this cluster work（as follow）? Could you  tell me how to do it and how did get the nine groups？What is it that determines the 9 cluster？
![image](https://github.com/vlothec/TRASH/assets/58722433/9c39a6be-bda7-4eb7-943f-9e1f443865c1)

Best

**Comment by vlothec** [comment]
Clustering was done using the hclust function from stats package in R, then it was plotted (fig 1D) and groups were extracted based on them
